# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='google_streaming_api.proto',
  package='content.proto',
  serialized_pb='\n\x1agoogle_streaming_api.proto\x12\rcontent.proto\"\x90\x03\n\x16SpeechRecognitionEvent\x12P\n\x06status\x18\x01 \x01(\x0e\x32\x30.content.proto.SpeechRecognitionEvent.StatusCode:\x0eSTATUS_SUCCESS\x12\x36\n\x06result\x18\x02 \x03(\x0b\x32&.content.proto.SpeechRecognitionResult\"\xeb\x01\n\nStatusCode\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x14\n\x10STATUS_NO_SPEECH\x10\x01\x12\x12\n\x0eSTATUS_ABORTED\x10\x02\x12\x18\n\x14STATUS_AUDIO_CAPTURE\x10\x03\x12\x12\n\x0eSTATUS_NETWORK\x10\x04\x12\x16\n\x12STATUS_NOT_ALLOWED\x10\x05\x12\x1e\n\x1aSTATUS_SERVICE_NOT_ALLOWED\x10\x06\x12\x16\n\x12STATUS_BAD_GRAMMAR\x10\x07\x12!\n\x1dSTATUS_LANGUAGE_NOT_SUPPORTED\x10\x08\"\x84\x01\n\x17SpeechRecognitionResult\x12@\n\x0b\x61lternative\x18\x01 \x03(\x0b\x32+.content.proto.SpeechRecognitionAlternative\x12\x14\n\x05\x66inal\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x11\n\tstability\x18\x03 \x01(\x02\"F\n\x1cSpeechRecognitionAlternative\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x42\x02H\x03')



_SPEECHRECOGNITIONEVENT_STATUSCODE = descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='content.proto.SpeechRecognitionEvent.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_NO_SPEECH', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_ABORTED', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_AUDIO_CAPTURE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_NETWORK', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_NOT_ALLOWED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_SERVICE_NOT_ALLOWED', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_BAD_GRAMMAR', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_LANGUAGE_NOT_SUPPORTED', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=211,
  serialized_end=446,
)


_SPEECHRECOGNITIONEVENT = descriptor.Descriptor(
  name='SpeechRecognitionEvent',
  full_name='content.proto.SpeechRecognitionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='content.proto.SpeechRecognitionEvent.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='content.proto.SpeechRecognitionEvent.result', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPEECHRECOGNITIONEVENT_STATUSCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=446,
)


_SPEECHRECOGNITIONRESULT = descriptor.Descriptor(
  name='SpeechRecognitionResult',
  full_name='content.proto.SpeechRecognitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='alternative', full_name='content.proto.SpeechRecognitionResult.alternative', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='final', full_name='content.proto.SpeechRecognitionResult.final', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stability', full_name='content.proto.SpeechRecognitionResult.stability', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=449,
  serialized_end=581,
)


_SPEECHRECOGNITIONALTERNATIVE = descriptor.Descriptor(
  name='SpeechRecognitionAlternative',
  full_name='content.proto.SpeechRecognitionAlternative',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='transcript', full_name='content.proto.SpeechRecognitionAlternative.transcript', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confidence', full_name='content.proto.SpeechRecognitionAlternative.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=583,
  serialized_end=653,
)

_SPEECHRECOGNITIONEVENT.fields_by_name['status'].enum_type = _SPEECHRECOGNITIONEVENT_STATUSCODE
_SPEECHRECOGNITIONEVENT.fields_by_name['result'].message_type = _SPEECHRECOGNITIONRESULT
_SPEECHRECOGNITIONEVENT_STATUSCODE.containing_type = _SPEECHRECOGNITIONEVENT;
_SPEECHRECOGNITIONRESULT.fields_by_name['alternative'].message_type = _SPEECHRECOGNITIONALTERNATIVE
DESCRIPTOR.message_types_by_name['SpeechRecognitionEvent'] = _SPEECHRECOGNITIONEVENT
DESCRIPTOR.message_types_by_name['SpeechRecognitionResult'] = _SPEECHRECOGNITIONRESULT
DESCRIPTOR.message_types_by_name['SpeechRecognitionAlternative'] = _SPEECHRECOGNITIONALTERNATIVE

class SpeechRecognitionEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPEECHRECOGNITIONEVENT
  
  # @@protoc_insertion_point(class_scope:content.proto.SpeechRecognitionEvent)

class SpeechRecognitionResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPEECHRECOGNITIONRESULT
  
  # @@protoc_insertion_point(class_scope:content.proto.SpeechRecognitionResult)

class SpeechRecognitionAlternative(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPEECHRECOGNITIONALTERNATIVE
  
  # @@protoc_insertion_point(class_scope:content.proto.SpeechRecognitionAlternative)

# @@protoc_insertion_point(module_scope)
